package myorganization.myproject.rules;

global java.util.ArrayList globalList;

rule "WHAT DATA DOES THIS HAVE"

    when
        myorganization.myproject.bom.MyObject( $myDate : myDate, $myDescription : myDescription, $myID : myID)
    then
        System.out.println("$myDate : "+$myDate);
        System.out.println("$myDescription : "+$myDescription);
        System.out.println("$myID : "+$myID);
        
end

rule "MY FIRST RULE"

    when
        myorganization.myproject.bom.MyObject( myID == 0 )
    then
        myorganization.myproject.bom.GlobalResponses globalResponses = new myorganization.myproject.bom.GlobalResponses();
        globalResponses.setRuleName("MY FIRST RULE");
        globalResponses.setRuleResponse("MY ID IS 0");
        globalList.add(globalResponses);
        System.out.println("MY ID IS 0");
        
end