package myorganization.myproject.process;

rule "MY SECOND PROCESS RULE"
    no-loop true
    ruleflow-group "all"
    when
        $myObject : myorganization.myproject.bom.MyObject( myID == 0 )
    then
        System.out.println("MY SECOND PROCESS RULE");
        System.out.println("AN OBJECT WITHOUT DESCRIPTION");
        $myObject.setMyDescription("AN OBJECT WITHOUT DESCRIPTION");
        update($myObject);
        
end